name: Azure Deploy (Reference Only)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure (Simulation)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Simulated Deployment
        run: |
          echo "This is a simulated deployment step"
          echo "az deployment group create --resource-group demo-group --template-file ./infra/main.bicep"
